version: 2

project_name: fastmail-cli

builds:
  - main: ./cmd/fastmail-cli
    binary: fastmail-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/seanb4t/fastmail-cli/cli.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: darwin
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^ci'
      - '^refactor'
      - '^test'
      - '^build'
      - '^style'
